//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Farsica.Template.Resource.Data.ViewModel.ApplicationSettings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApplicationSettingsViewModel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationSettingsViewModel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Farsica.Template.Resource.Data.ViewModel.ApplicationSettings.ApplicationSettingsViewModel" +
                            "", typeof(ApplicationSettingsViewModel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Limits Cron Job.
        /// </summary>
        public static string ApplyLimitsCronJob_Name {
            get {
                return ResourceManager.GetString("ApplyLimitsCronJob_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication Service Timeout.
        /// </summary>
        public static string AuthenticationServiceTimeout_Name {
            get {
                return ResourceManager.GetString("AuthenticationServiceTimeout_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication Service Url.
        /// </summary>
        public static string AuthenticationServiceUrl_Name {
            get {
                return ResourceManager.GetString("AuthenticationServiceUrl_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication Valid Domains.
        /// </summary>
        public static string AuthenticationValidDomains_Name {
            get {
                return ResourceManager.GetString("AuthenticationValidDomains_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default time zone.
        /// </summary>
        public static string DefaultTimeZoneId_Name {
            get {
                return ResourceManager.GetString("DefaultTimeZoneId_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid page size.
        /// </summary>
        public static string GridPageSize_Name {
            get {
                return ResourceManager.GetString("GridPageSize_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Message Broker Address.
        /// </summary>
        public static string NotificationMessageBrokerAddress_Name {
            get {
                return ResourceManager.GetString("NotificationMessageBrokerAddress_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Message Broker Password.
        /// </summary>
        public static string NotificationMessageBrokerPassword_Name {
            get {
                return ResourceManager.GetString("NotificationMessageBrokerPassword_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Message Broker Timeout in seconds.
        /// </summary>
        public static string NotificationMessageBrokerTimeout_Name {
            get {
                return ResourceManager.GetString("NotificationMessageBrokerTimeout_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Message Broker Username.
        /// </summary>
        public static string NotificationMessageBrokerUsername_Name {
            get {
                return ResourceManager.GetString("NotificationMessageBrokerUsername_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swagger Enabled.
        /// </summary>
        public static string SwaggerEnabled_Name {
            get {
                return ResourceManager.GetString("SwaggerEnabled_Name", resourceCulture);
            }
        }
    }
}
